"""
Evaluate supernode grouping quality on Neuronpedia graphs across four conditions.

All conditions use our pipeline's feature descriptions (generated by
generate_description.py), so the comparison is purely about grouping quality,
not description quality.

Conditions (toggle via VALIDATION_CONDITIONS env var, default: all four):
  - random                  : ours-full groups, features shuffled across them
  - human                   : manual_groups.json (from Neuronpedia share URL supernodes)
  - ours-full               : auto pipeline output AFTER phase-3 reconciliation
  - ours-no-reconciliation  : auto pipeline output BEFORE phase-3 (snapshot file)

Other env knobs:
  VALIDATION_MIN_GROUP_SIZE  groups with < N members are excluded (both sides).
  VALIDATION_DIFFICULTY      "medium" (default) | "both" (legacy easy+medium).

Output files (suffixed `_neuropedia`):
  validation_report_<desc>_<group>_neuropedia.json
  validation_report_<desc>_<group>_neuropedia.md
  validation_history_<desc>_<group>_neuropedia.json

For sweeping over min_group_size, see run_validation_sweep.py.

Group-level methods:

  Method 1 — Feature identification (1-in-10):
      For each feature in a group (up to 5), present its description among 9
      negative descriptions. Ask the model to pick the one that best matches
      the group name. Score: binary accuracy (1 if correct, 0 if wrong).
      Random chance baseline: 10%.

  Method 2 — Text snippet matching (5-in-10):
      Present 5 positive text snippets (from group features) and 5 negative
      snippets. Tell the model exactly 5 are from the group. Score: fraction
      of the 5 positives correctly identified (|correct ∩ actual| / 5).
      Random chance baseline: 50%.

Reads:  artifacts/<slug>/feature_descriptions_<desc>.json
        artifacts/<slug>/feature_groups_<desc>_<group>.json
        artifacts/<slug>/feature_groups_<desc>_<group>_pre3.json  (optional)
        artifacts/<slug>/manual_groups.json                       (optional)
Writes: artifacts/<slug>/validation_report_<desc>_<group>_neuropedia.json
        artifacts/<slug>/validation_history_<desc>_<group>_neuropedia.json

Usage:
    OPENAI_API_KEY=sk-xxx CURRENT_SLUG=<slug> python validate_neuropedia_groups.py
"""

from __future__ import annotations

import asyncio
import json
import math
import os
import random
import re
import sys
from collections import defaultdict
from pathlib import Path
from datetime import datetime, timezone
from typing import Any
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from openai import AsyncOpenAI  # noqa: F401  (kept for backwards compat / type hints)
from pydantic import BaseModel, Field

from config import (
    ARTIFACTS_DIR as _CONFIG_ARTIFACTS_DIR,  # noqa: F401  (kept for back-compat)
    CURRENT_SLUG,
    DESCRIPTION_VARIANT,
    FEATURE_DESCRIPTIONS_FILE as _CONFIG_FEATURE_DESCRIPTIONS_FILE,
    FEATURE_GROUPS_FILE as _CONFIG_FEATURE_GROUPS_FILE,
    FEATURE_GROUPS_PRE3_FILE as _CONFIG_FEATURE_GROUPS_PRE3_FILE,
    GRAPH_FILE as _CONFIG_GRAPH_FILE,
    GROUPING_MODEL,
    GROUPING_TOP_K_SEED,
    GROUPING_VARIANT,
    MANUAL_GROUPS_FILE as _CONFIG_MANUAL_GROUPS_FILE,
    PACKAGE_DIR,
    REPO_ROOT,
    VALIDATION_CONDITIONS,
    VALIDATION_DIFFICULTY,
    VALIDATION_HISTORY_FILE,
    VALIDATION_MIN_GROUP_SIZE,
    VALIDATION_REPORT_FILE,
    setup_logging,
)
from llm_client import get_client

log = setup_logging()

# ---------------------------------------------------------------------------
# Neuronpedia path overrides
# ---------------------------------------------------------------------------
# All Neuronpedia inputs (graphs + per-slug artifacts) now live in
# `test_graphs_neuronpedia/` and `custom_automation/artifacts_neuronpedia/`.
# Rebase the paths imported from config so this validator reads/writes from
# the Neuronpedia tree without disturbing config.py defaults used elsewhere.
NEURONPEDIA_TEST_GRAPHS_DIR = REPO_ROOT / "test_graphs_neuronpedia"
_NEURONPEDIA_ARTIFACTS_ROOT = PACKAGE_DIR / "artifacts_neuronpedia"
ARTIFACTS_DIR = (
    _NEURONPEDIA_ARTIFACTS_ROOT / CURRENT_SLUG if CURRENT_SLUG else _NEURONPEDIA_ARTIFACTS_ROOT
)

GRAPH_FILE = (
    NEURONPEDIA_TEST_GRAPHS_DIR / f"{CURRENT_SLUG}.json"
    if CURRENT_SLUG else NEURONPEDIA_TEST_GRAPHS_DIR / "test-run.json"
)
FEATURE_DESCRIPTIONS_FILE = ARTIFACTS_DIR / _CONFIG_FEATURE_DESCRIPTIONS_FILE.name
FEATURE_GROUPS_FILE = ARTIFACTS_DIR / _CONFIG_FEATURE_GROUPS_FILE.name
FEATURE_GROUPS_PRE3_FILE = ARTIFACTS_DIR / _CONFIG_FEATURE_GROUPS_PRE3_FILE.name
MANUAL_GROUPS_FILE = ARTIFACTS_DIR / _CONFIG_MANUAL_GROUPS_FILE.name

# When running with a non-OpenAI validator, route every per-slug validator
# output (report, history, markdown, D1/D2 cache) into a dedicated provider
# tree so GPT-produced files are not overwritten. Default (LLM_PROVIDER unset
# / 'openai') keeps every output inside the existing per-slug ARTIFACTS_DIR
# exactly as before.
_PROVIDER_OUTPUT_DIRS: dict[str, str] = {
    "anthropic": "anthropic_validations",
    "google":    "gemini_validations",
    "gemini":    "gemini_validations",
}
_PROVIDER = os.environ.get("LLM_PROVIDER", "openai").lower()
_NON_OPENAI_DIR_NAME = _PROVIDER_OUTPUT_DIRS.get(_PROVIDER)

if _NON_OPENAI_DIR_NAME:
    _VALIDATOR_OUT_DIR = PACKAGE_DIR / _NON_OPENAI_DIR_NAME
    if CURRENT_SLUG:
        _VALIDATOR_OUT_DIR = _VALIDATOR_OUT_DIR / CURRENT_SLUG
    _VALIDATOR_OUT_DIR.mkdir(parents=True, exist_ok=True)
else:
    _VALIDATOR_OUT_DIR = ARTIFACTS_DIR

VALIDATION_REPORT_FILE = _VALIDATOR_OUT_DIR / (
    VALIDATION_REPORT_FILE.stem + "_neuropedia" + VALIDATION_REPORT_FILE.suffix
)
VALIDATION_HISTORY_FILE = _VALIDATOR_OUT_DIR / (
    VALIDATION_HISTORY_FILE.stem + "_neuropedia" + VALIDATION_HISTORY_FILE.suffix
)
VALIDATION_MARKDOWN_FILE = VALIDATION_REPORT_FILE.with_suffix(".md")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Override either the grouping model entirely or the validator separately.
# Default keeps GPT runs identical to before.
VALIDATION_MODEL: str = os.environ.get("VALIDATION_MODEL", GROUPING_MODEL)
# OpenAI happily handles 500 concurrent calls; Anthropic / Google tier-2 limits
# (~50 RPM by default) get hammered, the validator's try/except silently catches
# the 429s as zero-score tasks, and macro_avg collapses. Default lower for the
# non-OpenAI providers and let the env override.
_DEFAULT_CONCURRENCY = 8 if _NON_OPENAI_DIR_NAME else 500
CONCURRENCY_LIMIT: int = int(os.environ.get("VALIDATION_CONCURRENCY", _DEFAULT_CONCURRENCY))
MIN_GROUP_SIZE = VALIDATION_MIN_GROUP_SIZE
DIFFICULTY = VALIDATION_DIFFICULTY if VALIDATION_DIFFICULTY in ("medium", "both") else "medium"
BASE_CONDITIONS = ("random", "human", "ours-full", "ours-no-reconciliation")
_OURS_CAP_RE      = re.compile(r"^ours-cap(\d+)$")
_OURS_CAP_PRE3_RE = re.compile(r"^ours-cap(\d+)-no-reconciliation$")
MAX_FEATURES_M1 = 5
N_NEG_FEATURES_M1 = 9
N_POS_SNIPPETS_M2 = 5
N_NEG_SNIPPETS_M2 = 5
# Description-level metrics — operate per-feature (independent of grouping
# condition or min_group_size). Cached per slug so repeated validation runs
# at different min_sizes don't re-pay the API cost.
MAX_FEATURES_D1 = 50
N_NEG_DESCS_D1 = 9
MAX_FEATURES_D2 = 50
N_POS_SNIPPETS_D2 = 5
N_NEG_SNIPPETS_D2 = 5
DESCRIPTION_METRICS_FILE = _VALIDATOR_OUT_DIR / f"description_metrics_{DESCRIPTION_VARIANT}_neuropedia.json"
RANDOM_SEED = 42
N_RUNS = 5


def discover_cap_conditions() -> list[str]:
    """Find every cap variant the cap-sweep produced.

    Returns both the post-phase-3 (`ours-cap<N>`) and pre-phase-3
    (`ours-cap<N>-no-reconciliation`) variants for each N that has the
    matching file present. Ascending by N for stable report ordering.
    """
    post_pat = re.compile(rf"^feature_groups_{re.escape(DESCRIPTION_VARIANT)}_"
                          rf"{re.escape(GROUPING_VARIANT)}_cap(\d+)\.json$")
    pre3_pat = re.compile(rf"^feature_groups_{re.escape(DESCRIPTION_VARIANT)}_"
                          rf"{re.escape(GROUPING_VARIANT)}_cap(\d+)_pre3\.json$")
    found: list[tuple[int, int, str]] = []  # (N, post-then-pre3-rank, name)
    for f in ARTIFACTS_DIR.glob(f"feature_groups_{DESCRIPTION_VARIANT}_{GROUPING_VARIANT}_cap*.json"):
        m_pre = pre3_pat.match(f.name)
        if m_pre:
            found.append((int(m_pre.group(1)), 1, f"ours-cap{m_pre.group(1)}-no-reconciliation"))
            continue
        m_post = post_pat.match(f.name)
        if m_post:
            found.append((int(m_post.group(1)), 0, f"ours-cap{m_post.group(1)}"))
    return [name for _, _, name in sorted(found)]


def all_available_conditions() -> tuple[str, ...]:
    return BASE_CONDITIONS + tuple(discover_cap_conditions())


def condition_sort_key(cond: str) -> tuple[int, int, int]:
    """Stable display order: random, human, ours-no-rec, ours-cap50…200 (pre then post), ours-full."""
    base = {"random": 0, "human": 1, "ours-no-reconciliation": 2, "ours-full": 999}
    if cond in base:
        return (base[cond], 0, 0)
    m_pre = _OURS_CAP_PRE3_RE.match(cond)
    if m_pre:
        # Pre-phase-3 variant sits just before its post-phase-3 sibling.
        return (10, int(m_pre.group(1)), 0)
    m = _OURS_CAP_RE.match(cond)
    if m:
        return (10, int(m.group(1)), 1)
    return (500, 0, 0)


def cap_n_from_condition(cond: str) -> int | None:
    """Cap N for either ours-cap<N> or ours-cap<N>-no-reconciliation; None otherwise."""
    m = _OURS_CAP_PRE3_RE.match(cond) or _OURS_CAP_RE.match(cond)
    return int(m.group(1)) if m else None


def cap_n_from_pre3_condition(cond: str) -> int | None:
    """Cap N if `cond` is ours-cap<N>-no-reconciliation; else None."""
    m = _OURS_CAP_PRE3_RE.match(cond)
    return int(m.group(1)) if m else None


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------

class SingleSelection(BaseModel):
    selected_index: int = Field(
        description="1-based index of the single feature that best matches the group."
    )


class FiveSelection(BaseModel):
    selected_indices: list[int] = Field(
        description="Exactly 5 unique 1-based indices of text snippets that belong to this group."
    )


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_data() -> tuple[list[dict], dict[str, str]]:
    if not FEATURE_DESCRIPTIONS_FILE.exists():
        log.error("Missing %s — run generate_description.py first.", FEATURE_DESCRIPTIONS_FILE)
        sys.exit(1)
    if not FEATURE_GROUPS_FILE.exists():
        log.error("Missing %s — run generate_supernodes.py first.", FEATURE_GROUPS_FILE)
        sys.exit(1)

    with open(FEATURE_DESCRIPTIONS_FILE, encoding="utf-8") as f:
        features: list[dict] = json.load(f)
    with open(FEATURE_GROUPS_FILE, encoding="utf-8") as f:
        groups: dict[str, str] = json.load(f)

    return features, groups


def build_group_index(
    features: list[dict], groups: dict[str, str]
) -> dict[str, list[dict]]:
    id_to_feature = {f["id"]: f for f in features if "id" in f}
    index: dict[str, list[dict]] = {}

    for fid, gname in groups.items():
        if gname in ("Ungrouped",) or gname.startswith(('Emb: "', 'Output: "')):
            continue
        feat = id_to_feature.get(fid)
        if feat and feat.get("generated_description"):
            index.setdefault(gname, []).append(feat)

    return index


def create_random_group_index(
    all_features: list[dict], group_index: dict[str, list[dict]], rng: random.Random
) -> dict[str, list[dict]]:
    """Shuffle ALL described features into the group structure regardless of influence score.

    Drawing from the entire feature set (grouped + ungrouped, all influence levels)
    gives a true random baseline — the positive is a genuinely random feature,
    not just pre-selected high-impact ones.
    """
    pool = [f for f in all_features if f.get("generated_description")]
    total_slots = sum(len(feats) for feats in group_index.values())
    if len(pool) < total_slots:
        log.warning(
            "[Random] Pool has %d features but %d slots needed — "
            "some groups will have fewer members.",
            len(pool), total_slots,
        )
    rng.shuffle(pool)
    random_index: dict[str, list[dict]] = {}
    idx = 0
    for group_name, feats in group_index.items():
        size = len(feats)
        random_index[group_name] = pool[idx: idx + size]
        idx += size
    return random_index


def load_condition_groups(
    condition: str,
    features: list[dict],
) -> tuple[dict[str, str], dict[str, list[dict]]] | None:
    if condition == "human":
        if not MANUAL_GROUPS_FILE.exists():
            log.info("[human] %s missing — skipping condition.", MANUAL_GROUPS_FILE)
            return None
        with open(MANUAL_GROUPS_FILE, encoding="utf-8") as f:
            groups: dict[str, str] = json.load(f)
        index = build_group_index(features, groups)
        if not index:
            log.warning("[human] No usable groups in %s.", MANUAL_GROUPS_FILE)
            return None
        return groups, index

    if condition == "ours-full":
        if not FEATURE_GROUPS_FILE.exists():
            log.error("[ours-full] %s missing — run generate_supernodes.py first.", FEATURE_GROUPS_FILE)
            return None
        with open(FEATURE_GROUPS_FILE, encoding="utf-8") as f:
            groups = json.load(f)
        index = build_group_index(features, groups)
        return (groups, index) if index else None

    if condition == "ours-no-reconciliation":
        if not FEATURE_GROUPS_PRE3_FILE.exists():
            log.warning("[ours-no-reconciliation] %s missing.", FEATURE_GROUPS_PRE3_FILE)
            return None
        with open(FEATURE_GROUPS_PRE3_FILE, encoding="utf-8") as f:
            groups = json.load(f)
        index = build_group_index(features, groups)
        return (groups, index) if index else None

    cap_n = cap_n_from_condition(condition)
    if cap_n is not None:
        is_pre3 = cap_n_from_pre3_condition(condition) is not None
        suffix = "_pre3" if is_pre3 else ""
        cap_file = ARTIFACTS_DIR / (
            f"feature_groups_{DESCRIPTION_VARIANT}_{GROUPING_VARIANT}_cap{cap_n}{suffix}.json"
        )
        if not cap_file.exists():
            log.info("[%s] %s missing — skipping condition.", condition, cap_file)
            return None
        with open(cap_file, encoding="utf-8") as f:
            groups = json.load(f)
        index = build_group_index(features, groups)
        return (groups, index) if index else None

    log.error("Unknown condition '%s'.", condition)
    return None


# ---------------------------------------------------------------------------
# Negative pool builders
# ---------------------------------------------------------------------------

def build_medium_neg_pool(features: list[dict], groups: dict[str, str]) -> list[dict]:
    pool: list[dict] = []
    for f in features:
        fid = f.get("id")
        if not fid:
            continue
        gname = groups.get(fid, "Ungrouped")
        if gname.startswith(('Emb: "', 'Output: "')):
            continue
        if gname == "Ungrouped" and f.get("generated_description"):
            pool.append(f)
    return pool


def build_hard_neg_pool(features: list[dict]) -> list[dict]:
    sorted_feats = sorted(
        [f for f in features if "influence_score" in f],
        key=lambda f: float(f.get("influence_score", 0.0)),
        reverse=True,
    )
    return [
        f for f in sorted_feats[GROUPING_TOP_K_SEED:]
        if f.get("generated_description")
    ]


# ---------------------------------------------------------------------------
# Snippet formatting
# ---------------------------------------------------------------------------

def _format_snippet(act: dict) -> str:
    context = act.get("context", "").strip()
    trigger = act.get("trigger", "").strip()
    if trigger and trigger in context:
        return context.replace(trigger, f"<<<{trigger}>>>", 1)
    if trigger:
        return f"{context} [Activates on: <<<{trigger}>>>]"
    return context


def _get_formatted_snippets(feat: dict, max_n: int = 5) -> list[str]:
    return [
        _format_snippet(act)
        for act in feat.get("top_activations", [])[:max_n]
        if act.get("context", "").strip()
    ]


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

def build_m1_prompt(group_name: str, items: list[tuple[str, bool]]) -> str:
    n = len(items)
    lines = [
        f'Group: "{group_name}"\n',
        f"Below are {n} feature descriptions from neurons inside a language model. "
        "Exactly 1 of these belongs to the group above.\n",
        "Pick the single feature description that best matches the group.\n",
    ]
    for i, (desc, _) in enumerate(items, 1):
        lines.append(f"{i}. {desc}")
    lines.append("\nRespond with the 1-based index of the best match.")
    return "\n".join(lines)


def build_m2_prompt(group_name: str, items: list[tuple[str, bool]], n_pos: int) -> str:
    n = len(items)
    lines = [
        f'Group: "{group_name}"\n',
        f"Below are {n} text excerpts that strongly activated neurons inside a "
        "language model. The key activating tokens are highlighted with <<<>>>. "
        f"Exactly {n_pos} of these come from neurons in this group.\n",
        f"Identify which {n_pos} text excerpts belong to this group.\n",
    ]
    for i, (snippet, _) in enumerate(items, 1):
        lines.append(f"{i}. {snippet}")
    lines.append(
        f"\nRespond with the 1-based indices of the {n_pos} excerpts from this group."
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Individual task runners
# ---------------------------------------------------------------------------

async def run_m1_trial(
    group_name: str,
    prompt: str,
    correct_idx: int,
    n_items: int,
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
) -> float:
    async with sem:
        try:
            resp = await client.beta.chat.completions.parse(
                model=VALIDATION_MODEL,
                messages=[{"role": "user", "content": prompt}],
                response_format=SingleSelection
            )
            parsed = resp.choices[0].message.parsed
            picked = parsed.selected_index if parsed else -1
        except Exception as exc:
            log.warning("[M1] %s: API error — %s", group_name, exc)
            picked = -1

    if picked < 1 or picked > n_items:
        return 0.0
    return 1.0 if picked == correct_idx else 0.0


async def run_m2_task(
    group_name: str,
    prompt: str,
    actual_positive_indices: set[int],
    n_items: int,
    n_expected: int,
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
) -> float:
    async with sem:
        try:
            resp = await client.beta.chat.completions.parse(
                model=VALIDATION_MODEL,
                messages=[{"role": "user", "content": prompt}],
                response_format=FiveSelection
            )
            parsed = resp.choices[0].message.parsed
            if parsed is None:
                return 0.0
            raw_indices = parsed.selected_indices
        except Exception as exc:
            log.warning("[M2] %s: API error — %s", group_name, exc)
            return 0.0

    valid_indices = [i for i in raw_indices if 1 <= i <= n_items]
    unique_valid = list(dict.fromkeys(valid_indices))

    if len(unique_valid) != n_expected:
        return 0.0

    predicted = set(unique_valid)
    return len(predicted & actual_positive_indices) / len(actual_positive_indices)


# ---------------------------------------------------------------------------
# Task generation — M1
# ---------------------------------------------------------------------------

def generate_m1_tasks(
    group_index: dict[str, list[dict]],
    seed: int,
    external_neg_pool: list[dict] | None = None,
) -> list[dict]:
    rng = random.Random(seed)
    tasks: list[dict] = []

    for group_name, pos_features in group_index.items():
        if len(pos_features) < MIN_GROUP_SIZE:
            continue

        neg_pool = external_neg_pool if external_neg_pool is not None else [
            f for gname, feats in group_index.items()
            if gname != group_name
            for f in feats
        ]
        if not neg_pool:
            continue

        test_features = (
            list(pos_features) if len(pos_features) <= MAX_FEATURES_M1
            else rng.sample(pos_features, MAX_FEATURES_M1)
        )

        for pos_feat in test_features:
            n_neg = min(len(neg_pool), N_NEG_FEATURES_M1)
            neg_feats = rng.sample(neg_pool, n_neg)

            items: list[tuple[str, bool]] = [
                (pos_feat.get("generated_description", "No description"), True)
            ] + [
                (f.get("generated_description", "No description"), False)
                for f in neg_feats
            ]
            rng.shuffle(items)

            correct_idx = next(i + 1 for i, (_, is_pos) in enumerate(items) if is_pos)

            tasks.append({
                "group_name": group_name,
                "prompt": build_m1_prompt(group_name, items),
                "correct_idx": correct_idx,
                "n_items": len(items),
            })

    return tasks


# ---------------------------------------------------------------------------
# Task generation — M2
# ---------------------------------------------------------------------------

def generate_m2_tasks(
    group_index: dict[str, list[dict]],
    seed: int,
    external_neg_pool: list[dict] | None = None,
) -> list[dict]:
    rng = random.Random(seed)
    tasks: list[dict] = []

    for group_name, pos_features in group_index.items():
        if len(pos_features) < MIN_GROUP_SIZE:
            continue

        all_pos_snippets = [
            s for f in pos_features for s in _get_formatted_snippets(f)
        ]
        if len(all_pos_snippets) < N_POS_SNIPPETS_M2:
            log.warning("[M2] %s: only %d snippets (need %d), skipping.",
                        group_name, len(all_pos_snippets), N_POS_SNIPPETS_M2)
            continue

        pos_snippets = rng.sample(all_pos_snippets, N_POS_SNIPPETS_M2)

        neg_snippet_pool = (
            [s for f in external_neg_pool for s in _get_formatted_snippets(f)]
            if external_neg_pool is not None
            else [
                s
                for gname, feats in group_index.items()
                if gname != group_name
                for f in feats
                for s in _get_formatted_snippets(f)
            ]
        )
        n_neg = min(len(neg_snippet_pool), N_NEG_SNIPPETS_M2)
        if n_neg == 0:
            log.warning("[M2] %s: no negative snippets available, skipping.", group_name)
            continue
        neg_snippets = rng.sample(neg_snippet_pool, n_neg)

        items: list[tuple[str, bool]] = (
            [(s, True) for s in pos_snippets] +
            [(s, False) for s in neg_snippets]
        )
        rng.shuffle(items)

        actual_positive_indices = {
            i + 1 for i, (_, is_pos) in enumerate(items) if is_pos
        }
        n_pos = len(pos_snippets)

        tasks.append({
            "group_name": group_name,
            "prompt": build_m2_prompt(group_name, items, n_pos),
            "actual_positive_indices": actual_positive_indices,
            "n_items": len(items),
            "n_expected": n_pos,
        })

    return tasks


# ---------------------------------------------------------------------------
# Run-level aggregation
# ---------------------------------------------------------------------------

def _stderr(values: list[float]) -> float:
    n = len(values)
    if n < 2:
        return 0.0
    mean = sum(values) / n
    variance = sum((v - mean) ** 2 for v in values) / (n - 1)
    return math.sqrt(variance / n)


def aggregate_by_run(
    tagged_results: list[tuple[int, str, float]],
) -> tuple[list[dict], dict[str, float]]:
    nested: dict[str, dict[int, list[float]]] = defaultdict(lambda: defaultdict(list))
    for run_idx, group_name, score in tagged_results:
        nested[group_name][run_idx].append(score)

    per_group_stats: list[dict] = []
    for group_name in sorted(nested.keys()):
        run_means: list[float] = []
        total_trials = 0
        for run_idx in sorted(nested[group_name].keys()):
            trials = nested[group_name][run_idx]
            total_trials += len(trials)
            run_means.append(sum(trials) / len(trials))

        mean_acc = sum(run_means) / len(run_means)
        stderr_acc = _stderr(run_means)
        per_group_stats.append({
            "group": group_name,
            "mean_accuracy": round(mean_acc, 4),
            "stderr_accuracy": round(stderr_acc, 4),
            "n_runs": len(run_means),
            "total_trials": total_trials,
        })

    if per_group_stats:
        group_means = [s["mean_accuracy"] for s in per_group_stats]
        macro = {
            "mean_accuracy": round(sum(group_means) / len(group_means), 4),
            "stderr_accuracy": round(_stderr(group_means), 4),
        }
    else:
        macro = {"mean_accuracy": 0.0, "stderr_accuracy": 0.0}

    return per_group_stats, macro


# ---------------------------------------------------------------------------
# Attribution coverage
# ---------------------------------------------------------------------------

def compute_attribution_coverage(
    features: list[dict], groups: dict[str, str]
) -> float:
    id_to_score = {
        f["id"]: float(f.get("influence_score", 0.0))
        for f in features if "id" in f
    }
    total = sum(id_to_score.values())
    if total == 0.0:
        return 0.0
    annotated = sum(
        id_to_score.get(fid, 0.0)
        for fid, gname in groups.items()
        if gname not in ("Ungrouped",)
        and not gname.startswith(('Emb: "', 'Output: "'))
        and fid in id_to_score
    )
    return round(annotated / total, 4)


# ---------------------------------------------------------------------------
# Run all validation for one condition
# ---------------------------------------------------------------------------

async def run_condition(
    label: str,
    group_index: dict[str, list[dict]],
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
    medium_neg_pool: list[dict] | None = None,
) -> dict[str, Any]:
    valid_groups = {k: v for k, v in group_index.items() if len(v) >= MIN_GROUP_SIZE}
    empty_method: dict[str, Any] = {"groups": [], "macro_avg": {"mean_accuracy": 0.0, "stderr_accuracy": 0.0}}
    expected_sources = ("easy", "medium") if DIFFICULTY == "both" else ("medium",)
    if not valid_groups:
        log.warning("[%s] No valid groups for validation.", label)
        return {src: {"method1": empty_method, "method2": empty_method} for src in expected_sources}

    neg_sources: list[tuple[str, list[dict] | None]] = []
    if DIFFICULTY == "both":
        neg_sources.append(("easy", None))
    neg_sources.append(("medium", medium_neg_pool))

    all_m1_specs: list[tuple[str, int, dict]] = []
    all_m2_specs: list[tuple[str, int, dict]] = []

    for neg_source, ext_pool in neg_sources:
        if ext_pool is not None and len(ext_pool) < N_NEG_FEATURES_M1:
            log.warning("[%s/%s] Negative pool too small (%d), skipping.",
                        label, neg_source, len(ext_pool))
            continue
        for run_idx in range(N_RUNS):
            seed = RANDOM_SEED + run_idx
            for spec in generate_m1_tasks(valid_groups, seed, ext_pool):
                all_m1_specs.append((neg_source, run_idx, spec))
            for spec in generate_m2_tasks(valid_groups, seed, ext_pool):
                all_m2_specs.append((neg_source, run_idx, spec))

    log.info("[%s] Launching %d M1 + %d M2 tasks (easy/medium × %d runs)…",
             label, len(all_m1_specs), len(all_m2_specs), N_RUNS)

    m1_coros = [
        run_m1_trial(s["group_name"], s["prompt"], s["correct_idx"], s["n_items"], client, sem)
        for _, _, s in all_m1_specs
    ]
    m2_coros = [
        run_m2_task(s["group_name"], s["prompt"], s["actual_positive_indices"], s["n_items"], s["n_expected"], client, sem)
        for _, _, s in all_m2_specs
    ]

    all_raw = await asyncio.gather(*m1_coros, *m2_coros)
    m1_scores = all_raw[:len(m1_coros)]
    m2_scores = all_raw[len(m1_coros):]

    m1_by_source: dict[str, list[tuple[int, str, float]]] = defaultdict(list)
    m2_by_source: dict[str, list[tuple[int, str, float]]] = defaultdict(list)
    for (src, run_idx, spec), score in zip(all_m1_specs, m1_scores):
        m1_by_source[src].append((run_idx, spec["group_name"], score))
    for (src, run_idx, spec), score in zip(all_m2_specs, m2_scores):
        m2_by_source[src].append((run_idx, spec["group_name"], score))

    results: dict[str, Any] = {}
    for neg_source in expected_sources:
        if neg_source not in m1_by_source and neg_source not in m2_by_source:
            results[neg_source] = {"method1": empty_method, "method2": empty_method}
            continue
        m1_groups, m1_macro = aggregate_by_run(m1_by_source.get(neg_source, []))
        m2_groups, m2_macro = aggregate_by_run(m2_by_source.get(neg_source, []))
        log.info("[%s/%s] M1: %.1f%% ± %.1f%%  M2: %.1f%% ± %.1f%%",
                 label, neg_source,
                 m1_macro["mean_accuracy"] * 100, m1_macro["stderr_accuracy"] * 100,
                 m2_macro["mean_accuracy"] * 100, m2_macro["stderr_accuracy"] * 100)
        results[neg_source] = {
            "method1": {"groups": m1_groups, "macro_avg": m1_macro, "total_trials": len(m1_by_source.get(neg_source, []))},
            "method2": {"groups": m2_groups, "macro_avg": m2_macro, "total_tasks": len(m2_by_source.get(neg_source, []))},
        }

    return results


async def run_random_condition(
    features: list[dict],
    group_index: dict[str, list[dict]],
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
    medium_neg_pool: list[dict] | None = None,
) -> dict[str, Any]:
    valid_groups = {k: v for k, v in group_index.items() if len(v) >= MIN_GROUP_SIZE}
    use_medium = (DIFFICULTY == "medium")
    neg_pool_arg = medium_neg_pool if use_medium else None
    neg_source_label = "medium" if use_medium else "easy"

    m1_specs: list[tuple[int, dict]] = []
    m2_specs: list[tuple[int, dict]] = []

    for run_idx in range(N_RUNS):
        seed = RANDOM_SEED + run_idx
        rng = random.Random(seed)
        shuffled = create_random_group_index(features, valid_groups, rng)

        for spec in generate_m1_tasks(shuffled, seed, neg_pool_arg):
            m1_specs.append((run_idx, spec))
        for spec in generate_m2_tasks(shuffled, seed, neg_pool_arg):
            m2_specs.append((run_idx, spec))

    log.info("[Random] Launching %d M1 + %d M2 tasks…", len(m1_specs), len(m2_specs))

    m1_coros = [
        run_m1_trial(s["group_name"], s["prompt"], s["correct_idx"], s["n_items"], client, sem)
        for _, s in m1_specs
    ]
    m2_coros = [
        run_m2_task(s["group_name"], s["prompt"], s["actual_positive_indices"], s["n_items"], s["n_expected"], client, sem)
        for _, s in m2_specs
    ]

    all_results = await asyncio.gather(*m1_coros, *m2_coros)
    m1_scores = all_results[:len(m1_coros)]
    m2_scores = all_results[len(m1_coros):]

    m1_tagged = [(ri, s["group_name"], sc) for (ri, s), sc in zip(m1_specs, m1_scores)]
    m2_tagged = [(ri, s["group_name"], sc) for (ri, s), sc in zip(m2_specs, m2_scores)]

    m1_groups, m1_macro = aggregate_by_run(m1_tagged)
    m2_groups, m2_macro = aggregate_by_run(m2_tagged)

    log.info("[Random/%s] M1: %.1f%% ± %.1f%%  M2: %.1f%% ± %.1f%%",
             neg_source_label,
             m1_macro["mean_accuracy"] * 100, m1_macro["stderr_accuracy"] * 100,
             m2_macro["mean_accuracy"] * 100, m2_macro["stderr_accuracy"] * 100)

    return {
        neg_source_label: {
            "method1": {"groups": m1_groups, "macro_avg": m1_macro, "total_trials": len(m1_tagged)},
            "method2": {"groups": m2_groups, "macro_avg": m2_macro, "total_tasks": len(m2_tagged)},
        }
    }


# ---------------------------------------------------------------------------
# Description-quality metrics — D1 / D2 (per-feature, slug-level)
# ---------------------------------------------------------------------------
#
# These tests evaluate how well the pipeline's auto-generated descriptions
# in feature_descriptions_<desc>.json fit each feature's actual evidence.
# They do not depend on grouping conditions or min_group_size, so we cache
# the result to DESCRIPTION_METRICS_FILE and reuse it across validation runs.
#
#   D1 — Description accuracy (1-in-10):
#       Show the model raw evidence for one feature (its top activations,
#       promoted/demoted tokens, prompt context); ask which of 10 candidate
#       descriptions matches. Tests if the description is uniquely identifiable.
#       Random chance: 10%.
#
#   D2 — Description snippet match (5-in-10):
#       Show the model a feature's description; ask which 5 of 10 snippets
#       activated this feature. Tests if the description correctly indicates
#       the activating examples. Random chance: 50%.
# ---------------------------------------------------------------------------


def _format_feature_evidence(feat: dict, prompt_text: str) -> str:
    """Format a feature's raw evidence (activations + output tokens) for D1 trials."""
    lines = [f"Feature {feat.get('id', '?')}:\n"]

    lines.append("--- PROMPT CONTEXT ---")
    lines.append(prompt_text)

    lines.append("\n--- INPUT ACTIVATIONS ---")
    for i, act in enumerate(feat.get("top_activations", [])[:10], 1):
        lines.append(f"Excerpt {i}: {_format_snippet(act)}")

    lines.append("\n--- GLOBAL OUTPUT TOKENS ---")
    promotes = feat.get("promotes", [])
    demotes = feat.get("demotes", [])
    lines.append(f"Top Promoted Tokens: {', '.join(promotes) if promotes else 'None available'}")
    lines.append(f"Top Demoted Tokens: {', '.join(demotes) if demotes else 'None available'}")

    return "\n".join(lines)


def build_d1_prompt(evidence: str, items: list[tuple[str, bool]]) -> str:
    """Method D1: given feature evidence, pick the 1 correct description from N."""
    n = len(items)
    lines = [
        "Below is evidence about a single feature neuron in a language model "
        "(its input activations and output tokens).\n",
        evidence,
        f"\nBelow are {n} candidate descriptions. Exactly 1 of these correctly "
        "describes this feature. Pick the single best match.\n",
    ]
    for i, (desc, _) in enumerate(items, 1):
        lines.append(f"{i}. {desc}")
    lines.append(
        "\nRespond with the 1-based index of the description that best matches "
        "the feature evidence above."
    )
    return "\n".join(lines)


def build_d2_prompt(description: str, items: list[tuple[str, bool]], n_pos: int) -> str:
    """Method D2: given a feature description, pick the n_pos snippets that activated it."""
    n = len(items)
    lines = [
        f'Feature description: "{description}"\n',
        f"Below are {n} text excerpts that strongly activated neurons inside a "
        "language model. The key activating tokens are highlighted with <<<>>>. "
        f"Exactly {n_pos} of these come from the neuron described above.\n",
        f"Identify which {n_pos} text excerpts match this feature description.\n",
    ]
    for i, (snippet, _) in enumerate(items, 1):
        lines.append(f"{i}. {snippet}")
    lines.append(
        f"\nRespond with the 1-based indices of the {n_pos} excerpts that activated this feature."
    )
    return "\n".join(lines)


def generate_d1_tasks(
    features: list[dict],
    prompt_text: str,
    seed: int,
    max_features: int = MAX_FEATURES_D1,
) -> list[dict]:
    """
    Generate Method D1 trial specs for one run.

    For each feature (up to max_features), present its evidence and a lineup
    of descriptions (1 correct + N_NEG_DESCS_D1 from other features).
    """
    rng = random.Random(seed)

    # Only features that have descriptions and activations
    eligible = [
        f for f in features
        if f.get("generated_description")
        and f.get("generated_description") != "Error generating description"
        and f.get("top_activations")
    ]

    if len(eligible) < 2:
        return []

    if len(eligible) > max_features:
        test_features = rng.sample(eligible, max_features)
    else:
        test_features = list(eligible)

    tasks: list[dict] = []
    for pos_feat in test_features:
        neg_pool = [f for f in eligible if f["id"] != pos_feat["id"]]
        if not neg_pool:
            continue

        n_neg = min(len(neg_pool), N_NEG_DESCS_D1)
        neg_feats = rng.sample(neg_pool, n_neg)

        items: list[tuple[str, bool]] = [
            (pos_feat["generated_description"], True)
        ] + [
            (f["generated_description"], False)
            for f in neg_feats
        ]
        rng.shuffle(items)

        correct_idx = next(i + 1 for i, (_, is_pos) in enumerate(items) if is_pos)
        evidence = _format_feature_evidence(pos_feat, prompt_text)

        tasks.append({
            "group_name": "description_accuracy",  # pseudo-group for aggregation
            "prompt": build_d1_prompt(evidence, items),
            "correct_idx": correct_idx,
            "n_items": len(items),
            "feature_id": pos_feat["id"],
        })

    return tasks


def generate_d2_tasks(
    features: list[dict],
    seed: int,
    max_features: int = MAX_FEATURES_D2,
) -> list[dict]:
    """
    Generate Method D2 trial specs for one run.

    For each feature (up to max_features), present its description alongside
    10 text snippets (N_POS_SNIPPETS_D2 from this feature + N_NEG_SNIPPETS_D2
    from other features). Ask the model to pick the ones that activated it.
    """
    rng = random.Random(seed)

    eligible = [
        f for f in features
        if f.get("generated_description")
        and f.get("generated_description") != "Error generating description"
        and len(_get_formatted_snippets(f)) >= N_POS_SNIPPETS_D2
    ]

    if len(eligible) < 2:
        return []

    if len(eligible) > max_features:
        test_features = rng.sample(eligible, max_features)
    else:
        test_features = list(eligible)

    tasks: list[dict] = []
    for pos_feat in test_features:
        pos_snippets = _get_formatted_snippets(pos_feat, N_POS_SNIPPETS_D2)

        neg_pool = [
            s
            for f in eligible
            if f["id"] != pos_feat["id"]
            for s in _get_formatted_snippets(f)
        ]
        if len(neg_pool) < N_NEG_SNIPPETS_D2:
            continue

        neg_snippets = rng.sample(neg_pool, N_NEG_SNIPPETS_D2)

        items: list[tuple[str, bool]] = (
            [(s, True) for s in pos_snippets] +
            [(s, False) for s in neg_snippets]
        )
        rng.shuffle(items)

        actual_positive_indices = {
            i + 1 for i, (_, is_pos) in enumerate(items) if is_pos
        }

        tasks.append({
            "group_name": "description_snippet_accuracy",  # pseudo-group for aggregation
            "prompt": build_d2_prompt(pos_feat["generated_description"], items, N_POS_SNIPPETS_D2),
            "actual_positive_indices": actual_positive_indices,
            "n_items": len(items),
            "n_expected": N_POS_SNIPPETS_D2,
            "feature_id": pos_feat["id"],
        })

    return tasks


async def run_description_metrics(
    features: list[dict],
    prompt_text: str,
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
) -> dict[str, Any]:
    """Run D1 + D2 across N_RUNS. Returns {d1: {...}, d2: {...}}."""
    d1_specs: list[tuple[int, dict]] = []
    d2_specs: list[tuple[int, dict]] = []
    for run_idx in range(N_RUNS):
        seed = RANDOM_SEED + run_idx
        for spec in generate_d1_tasks(features, prompt_text, seed):
            d1_specs.append((run_idx, spec))
        for spec in generate_d2_tasks(features, seed):
            d2_specs.append((run_idx, spec))

    log.info("[D1] %d trials  [D2] %d tasks  (×%d runs)",
             len(d1_specs) // max(1, N_RUNS), len(d2_specs) // max(1, N_RUNS), N_RUNS)

    d1_coros = [
        run_m1_trial(s["group_name"], s["prompt"], s["correct_idx"], s["n_items"], client, sem)
        for _, s in d1_specs
    ]
    d2_coros = [
        run_m2_task(s["group_name"], s["prompt"], s["actual_positive_indices"],
                    s["n_items"], s["n_expected"], client, sem)
        for _, s in d2_specs
    ]

    all_scores = await asyncio.gather(*d1_coros, *d2_coros)
    d1_scores = all_scores[: len(d1_coros)]
    d2_scores = all_scores[len(d1_coros):]

    d1_tagged = [(ri, spec["group_name"], sc) for (ri, spec), sc in zip(d1_specs, d1_scores)]
    d2_tagged = [(ri, spec["group_name"], sc) for (ri, spec), sc in zip(d2_specs, d2_scores)]
    _, d1_macro = aggregate_by_run(d1_tagged)
    _, d2_macro = aggregate_by_run(d2_tagged)

    log.info("[D1] %.1f%% ± %.1f%%  [D2] %.1f%% ± %.1f%%",
             d1_macro["mean_accuracy"] * 100, d1_macro["stderr_accuracy"] * 100,
             d2_macro["mean_accuracy"] * 100, d2_macro["stderr_accuracy"] * 100)

    return {
        "d1": {"macro_avg": d1_macro, "total_trials": len(d1_tagged)},
        "d2": {"macro_avg": d2_macro, "total_tasks": len(d2_tagged)},
    }


def load_or_compute_description_metrics(
    features: list[dict],
    prompt_text: str,
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
) -> "asyncio.Future[dict[str, Any]] | dict[str, Any]":
    """Return cached description metrics if present, else compute + cache."""
    if DESCRIPTION_METRICS_FILE.exists():
        try:
            with open(DESCRIPTION_METRICS_FILE, encoding="utf-8") as f:
                cached = json.load(f)
            log.info("[D1/D2] Reusing cached description metrics (%s)", DESCRIPTION_METRICS_FILE.name)
            return cached
        except (json.JSONDecodeError, OSError) as exc:
            log.warning("[D1/D2] Cache unreadable (%s) — recomputing.", exc)

    async def _compute_and_cache():
        result = await run_description_metrics(features, prompt_text, client, sem)
        DESCRIPTION_METRICS_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(DESCRIPTION_METRICS_FILE, "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2, ensure_ascii=False)
        log.info("[D1/D2] Cached → %s", DESCRIPTION_METRICS_FILE)
        return result

    return _compute_and_cache()


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

def _fmt_macro(d: dict) -> str:
    return f"{d.get('mean_accuracy', 0.0):.1%} ± {d.get('stderr_accuracy', 0.0):.1%}"


def _macro_for(report: dict, condition: str, neg_source: str, method: str) -> dict:
    return (
        report.get("conditions", {})
        .get(condition, {})
        .get(neg_source, {})
        .get(method, {})
        .get("macro_avg", {"mean_accuracy": 0.0, "stderr_accuracy": 0.0})
    )


def write_markdown_report(report: dict, path: Path) -> None:
    n_runs = report.get("n_runs", N_RUNS)
    chance_m1 = 1 / (1 + N_NEG_FEATURES_M1)
    chance_m2 = N_POS_SNIPPETS_M2 / (N_POS_SNIPPETS_M2 + N_NEG_SNIPPETS_M2)

    difficulty = report.get("difficulty", DIFFICULTY)
    sources = ("easy", "medium") if difficulty == "both" else ("medium",)
    conditions = report.get("conditions", {})

    L: list[str] = [
        "# Validation Report",
        "",
        f"**Prompt:** {report.get('prompt', 'Unknown')}",
        f"**Description variant:** `{DESCRIPTION_VARIANT}`  |  **Grouping variant:** `{GROUPING_VARIANT}`",
        f"**Min group size:** {report.get('min_group_size', MIN_GROUP_SIZE)}  |  "
        f"**Difficulty:** {difficulty}",
        f"**Date:** {report.get('timestamp', '')}  |  **Runs:** {n_runs}",
        "",
        "---",
        "",
        "## Method Scores by Condition",
        "",
        f"M1 = 1-in-{1+N_NEG_FEATURES_M1} feature ID (chance {chance_m1:.0%}). "
        f"M2 = {N_POS_SNIPPETS_M2}-in-{N_POS_SNIPPETS_M2+N_NEG_SNIPPETS_M2} text match (chance {chance_m2:.0%}). "
        "Scores are mean ± stderr across runs.",
        "",
    ]

    header_cells = ["Condition"] + [f"M1 ({s})" for s in sources] + [f"M2 ({s})" for s in sources] + ["Coverage", "Groups"]
    L.append("| " + " | ".join(header_cells) + " |")
    L.append("|" + "|".join([":--"] + ["---:"] * (len(header_cells) - 1)) + "|")

    for cond in sorted(conditions.keys(), key=condition_sort_key):
        c = conditions[cond]
        if c.get("skipped"):
            L.append(f"| **{cond}** | _skipped: {c.get('reason','')}_ |")
            continue
        cov = c.get("attribution_coverage")
        cov_str = f"{cov:.1%}" if cov is not None else "—"
        n_valid = c.get("n_groups_valid")
        groups_str = f"{n_valid}/{c.get('n_groups_total', '?')}" if n_valid is not None else "—"
        cells = [f"**{cond}**"]
        for s in sources:
            cells.append(_fmt_macro(_macro_for(report, cond, s, "method1")))
        for s in sources:
            cells.append(_fmt_macro(_macro_for(report, cond, s, "method2")))
        cells += [cov_str, groups_str]
        L.append("| " + " | ".join(cells) + " |")
    L += ["", "---", ""]

    # Description-quality metrics (slug-level, independent of condition / min_size)
    desc = report.get("description_metrics") or {}
    if desc:
        d1 = desc.get("d1", {}).get("macro_avg", {})
        d2 = desc.get("d2", {}).get("macro_avg", {})
        L += [
            "## Description Quality (D1 / D2)",
            "",
            "Per-feature tests of how well the auto-generated descriptions fit each feature's evidence. "
            "Slug-level (does not depend on grouping condition or min_group_size).",
            "",
            "| Method | Macro accuracy |",
            "|:--|---:|",
            f"| **D1** — feature evidence → description (1-in-{1+N_NEG_DESCS_D1}, chance {1/(1+N_NEG_DESCS_D1):.0%}) | {_fmt_macro(d1)} |",
            f"| **D2** — description → activating snippets ({N_POS_SNIPPETS_D2}-in-{N_POS_SNIPPETS_D2+N_NEG_SNIPPETS_D2}, chance {N_POS_SNIPPETS_D2/(N_POS_SNIPPETS_D2+N_NEG_SNIPPETS_D2):.0%}) | {_fmt_macro(d2)} |",
            "",
            "---",
            "",
        ]

    detail_cond = "ours-full" if "ours-full" in conditions else next(iter(conditions), None)
    if detail_cond:
        for s in sources:
            m1_groups = conditions.get(detail_cond, {}).get(s, {}).get("method1", {}).get("groups", [])
            if not m1_groups:
                continue
            L += [
                f"## Per-Group Detail — {detail_cond} / {s}",
                "",
                "| Group | M1 Accuracy | ±Stderr | Trials |",
                "|:--|---:|---:|---:|",
            ]
            for sg in sorted(m1_groups, key=lambda x: x["mean_accuracy"], reverse=True):
                L.append(
                    f"| {sg['group'][:55]} "
                    f"| {sg['mean_accuracy']:.1%} "
                    f"| {sg['stderr_accuracy']:.1%} "
                    f"| {sg['total_trials']} |"
                )
            L += [""]
            break

    L += [
        "---",
        "",
        f"*Generated {report.get('timestamp', '')} · "
        f"desc=`{DESCRIPTION_VARIANT}` · group=`{GROUPING_VARIANT}` · "
        f"min_group_size={report.get('min_group_size', MIN_GROUP_SIZE)}*",
    ]

    path.write_text("\n".join(L) + "\n", encoding="utf-8")
    log.info("Markdown report saved → %s", path)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read_prompt_from_graph() -> str:
    try:
        with open(GRAPH_FILE, encoding="utf-8") as f:
            data = json.load(f)
        meta = data.get("metadata", {})
        prompt = meta.get("prompt", "")
        if not prompt:
            tokens = meta.get("prompt_tokens", [])
            prompt = "".join(str(t) for t in tokens)
        return prompt or GRAPH_FILE.stem
    except Exception:
        return GRAPH_FILE.stem


def _count_named_groups(groups_raw: dict[str, str]) -> int:
    return len({
        g for g in groups_raw.values()
        if g != "Ungrouped" and not g.startswith(('Emb: "', 'Output: "'))
    })


def _resolve_requested_conditions() -> list[str]:
    available = all_available_conditions()
    raw = VALIDATION_CONDITIONS.strip()
    if not raw:
        return list(available)
    requested = [c.strip() for c in raw.split(",") if c.strip()]
    invalid = [
        c for c in requested
        if c not in available
        and not _OURS_CAP_RE.match(c)
        and not _OURS_CAP_PRE3_RE.match(c)
    ]
    if invalid:
        log.error("Unknown VALIDATION_CONDITIONS values: %s. Available: %s", invalid, available)
        sys.exit(1)
    return requested


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def main_async() -> None:
    if not FEATURE_DESCRIPTIONS_FILE.exists():
        log.error("Missing %s — run generate_description.py first.", FEATURE_DESCRIPTIONS_FILE)
        sys.exit(1)
    with open(FEATURE_DESCRIPTIONS_FILE, encoding="utf-8") as f:
        features: list[dict] = json.load(f)

    requested = _resolve_requested_conditions()
    log.info("Conditions: %s", requested)
    log.info("Min group size: %d  |  Difficulty: %s", MIN_GROUP_SIZE, DIFFICULTY)
    log.info("Validator model: %s  (provider=%s)", VALIDATION_MODEL, os.environ.get("LLM_PROVIDER", "openai"))

    client = get_client()
    sem = asyncio.Semaphore(CONCURRENCY_LIMIT)

    loaded: dict[str, tuple[dict[str, str], dict[str, list[dict]]]] = {}
    skipped: dict[str, str] = {}
    for cond in requested:
        if cond == "random":
            base = load_condition_groups("ours-full", features)
            if base is None:
                skipped[cond] = "ours-full base groups unavailable"
                continue
            loaded[cond] = base
        else:
            res = load_condition_groups(cond, features)
            if res is None:
                skipped[cond] = "data file missing"
                continue
            loaded[cond] = res

    coros: list[Any] = []
    cond_order: list[str] = []
    for cond in requested:
        if cond not in loaded:
            continue
        groups_raw, group_index = loaded[cond]
        medium_neg_pool = build_medium_neg_pool(features, groups_raw)
        log.info("[%s] Negative pool (medium): %d features", cond, len(medium_neg_pool))
        if cond == "random":
            coros.append(run_random_condition(features, group_index, client, sem, medium_neg_pool))
        else:
            coros.append(run_condition(cond, group_index, client, sem, medium_neg_pool))
        cond_order.append(cond)

    # Description-quality metrics (D1/D2). Cached per slug — only the first
    # validation run per slug pays the API cost; later runs at other min_sizes
    # reuse the result.
    prompt_text_for_eval = _read_prompt_from_graph()
    desc_metrics_or_coro = load_or_compute_description_metrics(
        features, prompt_text_for_eval, client, sem,
    )
    if asyncio.iscoroutine(desc_metrics_or_coro):
        coros.append(desc_metrics_or_coro)
        desc_metrics_pending = True
    else:
        description_metrics = desc_metrics_or_coro
        desc_metrics_pending = False

    gathered = await asyncio.gather(*coros) if coros else []
    n_cond = len(cond_order)
    cond_results_raw = gathered[:n_cond]
    if desc_metrics_pending:
        description_metrics = gathered[n_cond]

    condition_results: dict[str, Any] = {}
    for cond, out in zip(cond_order, cond_results_raw):
        groups_raw, group_index = loaded[cond]
        condition_results[cond] = {
            **out,
            "attribution_coverage": compute_attribution_coverage(features, groups_raw),
            "n_groups_total": _count_named_groups(groups_raw),
            "n_groups_valid": sum(1 for v in group_index.values() if len(v) >= MIN_GROUP_SIZE),
        }
    for cond, reason in skipped.items():
        condition_results[cond] = {"skipped": True, "reason": reason}

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    prompt_text = _read_prompt_from_graph()
    report: dict[str, Any] = {
        "prompt": prompt_text,
        "timestamp": timestamp,
        "n_runs": N_RUNS,
        "min_group_size": MIN_GROUP_SIZE,
        "difficulty": DIFFICULTY,
        "design": {
            "method1": f"1-in-{1+N_NEG_FEATURES_M1} feature identification (chance={1/(1+N_NEG_FEATURES_M1):.0%})",
            "method2": f"{N_POS_SNIPPETS_M2}-in-{N_POS_SNIPPETS_M2+N_NEG_SNIPPETS_M2} text snippet matching (chance={N_POS_SNIPPETS_M2/(N_POS_SNIPPETS_M2+N_NEG_SNIPPETS_M2):.0%})",
            "method_d1": f"1-in-{1+N_NEG_DESCS_D1} description accuracy — given feature evidence, pick correct description (chance={1/(1+N_NEG_DESCS_D1):.0%}); per-feature, slug-level (independent of grouping condition / min_group_size)",
            "method_d2": f"{N_POS_SNIPPETS_D2}-in-{N_POS_SNIPPETS_D2+N_NEG_SNIPPETS_D2} description snippet match — given description, pick activating snippets (chance={N_POS_SNIPPETS_D2/(N_POS_SNIPPETS_D2+N_NEG_SNIPPETS_D2):.0%}); per-feature, slug-level",
            "aggregation": "per-group run-level means, then mean ± stderr across runs",
            "neg_sources": "medium=Ungrouped/unassigned features (excluding Emb/Output)",
            "conditions": {
                "random": "ours-full groups, features shuffled across them",
                "human": "manual_groups.json — human labels from Neuronpedia share URL supernodes",
                "ours-full": "auto pipeline output after phase-3 reconciliation (no feature cap)",
                "ours-no-reconciliation": "auto pipeline output before phase-3 (snapshot)",
                "ours-cap<N>": "phase-2 cap sweep variant — only the top N most influential "
                               "features were fed to grouping (50 = phase 1 only). Phase 3 "
                               "still runs on top.",
            },
        },
        "conditions": condition_results,
        "description_metrics": description_metrics,
    }

    with open(VALIDATION_REPORT_FILE, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    log.info("Validation report saved → %s", VALIDATION_REPORT_FILE)

    write_markdown_report(report, VALIDATION_MARKDOWN_FILE)

    history: list[dict] = []
    if VALIDATION_HISTORY_FILE.exists():
        try:
            with open(VALIDATION_HISTORY_FILE, encoding="utf-8") as f:
                history = json.load(f)
        except json.JSONDecodeError:
            history = []
    history.append(report)
    with open(VALIDATION_HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2, ensure_ascii=False)
    log.info("Appended to history (%d total) → %s", len(history), VALIDATION_HISTORY_FILE)

    # Console summary
    chance_m1 = 1 / (1 + N_NEG_FEATURES_M1)
    chance_m2 = N_POS_SNIPPETS_M2 / (N_POS_SNIPPETS_M2 + N_NEG_SNIPPETS_M2)

    print(f"\n{'='*84}")
    print(f"  VALIDATION SUMMARY  ({N_RUNS} runs · min_group_size={MIN_GROUP_SIZE} · difficulty={DIFFICULTY})")
    print(f"  M1 chance={chance_m1:.0%}  M2 chance={chance_m2:.0%}")
    print(f"{'='*84}")

    sources = ("easy", "medium") if DIFFICULTY == "both" else ("medium",)
    header = (
        f"  {'Condition':<26}"
        + "".join(f"{'M1 ' + s:>16}" for s in sources)
        + "".join(f"{'M2 ' + s:>16}" for s in sources)
        + f"{'Coverage':>10}{'Groups':>10}"
    )
    print(header)
    print("  " + "-" * (len(header) - 2))
    for cond in sorted(condition_results.keys(), key=condition_sort_key):
        c = condition_results[cond]
        if c.get("skipped"):
            print(f"  {cond:<26}  skipped: {c.get('reason','')}")
            continue
        row = f"  {cond:<26}"
        for s in sources:
            m = _macro_for(report, cond, s, "method1")
            row += f"{m['mean_accuracy']*100:>8.1f}±{m['stderr_accuracy']*100:.1f}%  "
        for s in sources:
            m = _macro_for(report, cond, s, "method2")
            row += f"{m['mean_accuracy']*100:>8.1f}±{m['stderr_accuracy']*100:.1f}%  "
        cov = c.get("attribution_coverage")
        cov_str = f"{cov*100:.1f}%" if cov is not None else "  —  "
        n_valid = c.get("n_groups_valid", 0)
        n_total = c.get("n_groups_total", 0)
        row += f"{cov_str:>10}{f'{n_valid}/{n_total}':>10}"
        print(row)

    print(f"{'='*84}\n")


def main() -> None:
    asyncio.run(main_async())


if __name__ == "__main__":
    main()