"""
Evaluate supernode grouping quality on Neuronpedia graphs across four conditions.

All conditions use our pipeline's feature descriptions (generated by
generate_description.py), so the comparison is purely about grouping quality,
not description quality.

Conditions (toggle via VALIDATION_CONDITIONS env var, default: all four):
  - random                  : ours-full groups, features shuffled across them
  - human                   : manual_groups.json (from Neuronpedia share URL supernodes)
  - ours-full               : auto pipeline output AFTER phase-3 reconciliation
  - ours-no-reconciliation  : auto pipeline output BEFORE phase-3 (snapshot file)

Other env knobs:
  VALIDATION_MIN_GROUP_SIZE  groups with < N members are excluded (both sides).
  VALIDATION_DIFFICULTY      "medium" (default) | "both" (legacy easy+medium).

Output files (suffixed `_neuropedia`):
  validation_report_<desc>_<group>_neuropedia.json
  validation_report_<desc>_<group>_neuropedia.md
  validation_history_<desc>_<group>_neuropedia.json

For sweeping over min_group_size, see run_validation_sweep.py.

Group-level methods:

  Method 1 — Feature identification (1-in-10):
      For each feature in a group (up to 5), present its description among 9
      negative descriptions. Ask the model to pick the one that best matches
      the group name. Score: binary accuracy (1 if correct, 0 if wrong).
      Random chance baseline: 10%.

  Method 2 — Text snippet matching (5-in-10):
      Present 5 positive text snippets (from group features) and 5 negative
      snippets. Tell the model exactly 5 are from the group. Score: fraction
      of the 5 positives correctly identified (|correct ∩ actual| / 5).
      Random chance baseline: 50%.

Reads:  artifacts/<slug>/feature_descriptions_<desc>.json
        artifacts/<slug>/feature_groups_<desc>_<group>.json
        artifacts/<slug>/feature_groups_<desc>_<group>_pre3.json  (optional)
        artifacts/<slug>/manual_groups.json                       (optional)
Writes: artifacts/<slug>/validation_report_<desc>_<group>_neuropedia.json
        artifacts/<slug>/validation_history_<desc>_<group>_neuropedia.json

Usage:
    OPENAI_API_KEY=sk-xxx CURRENT_SLUG=<slug> python validate_neuropedia_groups.py
"""

from __future__ import annotations

import asyncio
import json
import math
import random
import re
import sys
from collections import defaultdict
from pathlib import Path
from datetime import datetime, timezone
from typing import Any
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from openai import AsyncOpenAI
from pydantic import BaseModel, Field

from config import (
    ARTIFACTS_DIR,
    DESCRIPTION_VARIANT,
    FEATURE_DESCRIPTIONS_FILE,
    FEATURE_GROUPS_FILE,
    FEATURE_GROUPS_PRE3_FILE,
    GRAPH_FILE,
    GROUPING_MODEL,
    GROUPING_TOP_K_SEED,
    GROUPING_VARIANT,
    MANUAL_GROUPS_FILE,
    VALIDATION_CONDITIONS,
    VALIDATION_DIFFICULTY,
    VALIDATION_HISTORY_FILE,
    VALIDATION_MIN_GROUP_SIZE,
    VALIDATION_REPORT_FILE,
    setup_logging,
)

log = setup_logging()

VALIDATION_REPORT_FILE = VALIDATION_REPORT_FILE.with_name(
    VALIDATION_REPORT_FILE.stem + "_neuropedia" + VALIDATION_REPORT_FILE.suffix
)
VALIDATION_HISTORY_FILE = VALIDATION_HISTORY_FILE.with_name(
    VALIDATION_HISTORY_FILE.stem + "_neuropedia" + VALIDATION_HISTORY_FILE.suffix
)
VALIDATION_MARKDOWN_FILE = VALIDATION_REPORT_FILE.with_suffix(".md")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

VALIDATION_MODEL = GROUPING_MODEL
CONCURRENCY_LIMIT = 500
MIN_GROUP_SIZE = VALIDATION_MIN_GROUP_SIZE
DIFFICULTY = VALIDATION_DIFFICULTY if VALIDATION_DIFFICULTY in ("medium", "both") else "medium"
BASE_CONDITIONS = ("random", "human", "ours-full", "ours-no-reconciliation")
_OURS_CAP_RE = re.compile(r"^ours-cap(\d+)$")
MAX_FEATURES_M1 = 5
N_NEG_FEATURES_M1 = 9
N_POS_SNIPPETS_M2 = 5
N_NEG_SNIPPETS_M2 = 5
RANDOM_SEED = 42
N_RUNS = 5


def discover_cap_conditions() -> list[str]:
    """Find every feature_groups_<desc>_<group>_cap<N>.json the cap-sweep produced.

    Returned ascending by N so the report renders 50 → 100 → 150 → 200.
    """
    pat = re.compile(rf"^feature_groups_{re.escape(DESCRIPTION_VARIANT)}_"
                     rf"{re.escape(GROUPING_VARIANT)}_cap(\d+)\.json$")
    found: list[tuple[int, str]] = []
    for f in ARTIFACTS_DIR.glob(f"feature_groups_{DESCRIPTION_VARIANT}_{GROUPING_VARIANT}_cap*.json"):
        if "_pre3" in f.name:
            continue
        m = pat.match(f.name)
        if m:
            found.append((int(m.group(1)), f"ours-cap{m.group(1)}"))
    return [name for _, name in sorted(found)]


def all_available_conditions() -> tuple[str, ...]:
    return BASE_CONDITIONS + tuple(discover_cap_conditions())


def condition_sort_key(cond: str) -> tuple[int, int]:
    """Stable display order: random, human, ours-no-rec, ours-cap50…200, ours-full."""
    base = {"random": 0, "human": 1, "ours-no-reconciliation": 2, "ours-full": 999}
    if cond in base:
        return (base[cond], 0)
    m = _OURS_CAP_RE.match(cond)
    if m:
        return (10, int(m.group(1)))
    return (500, 0)


def cap_n_from_condition(cond: str) -> int | None:
    m = _OURS_CAP_RE.match(cond)
    return int(m.group(1)) if m else None


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------

class SingleSelection(BaseModel):
    selected_index: int = Field(
        description="1-based index of the single feature that best matches the group."
    )


class FiveSelection(BaseModel):
    selected_indices: list[int] = Field(
        description="Exactly 5 unique 1-based indices of text snippets that belong to this group."
    )


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_data() -> tuple[list[dict], dict[str, str]]:
    if not FEATURE_DESCRIPTIONS_FILE.exists():
        log.error("Missing %s — run generate_description.py first.", FEATURE_DESCRIPTIONS_FILE)
        sys.exit(1)
    if not FEATURE_GROUPS_FILE.exists():
        log.error("Missing %s — run generate_supernodes.py first.", FEATURE_GROUPS_FILE)
        sys.exit(1)

    with open(FEATURE_DESCRIPTIONS_FILE, encoding="utf-8") as f:
        features: list[dict] = json.load(f)
    with open(FEATURE_GROUPS_FILE, encoding="utf-8") as f:
        groups: dict[str, str] = json.load(f)

    return features, groups


def build_group_index(
    features: list[dict], groups: dict[str, str]
) -> dict[str, list[dict]]:
    id_to_feature = {f["id"]: f for f in features if "id" in f}
    index: dict[str, list[dict]] = {}

    for fid, gname in groups.items():
        if gname in ("Ungrouped",) or gname.startswith(('Emb: "', 'Output: "')):
            continue
        feat = id_to_feature.get(fid)
        if feat and feat.get("generated_description"):
            index.setdefault(gname, []).append(feat)

    return index


def create_random_group_index(
    all_features: list[dict], group_index: dict[str, list[dict]], rng: random.Random
) -> dict[str, list[dict]]:
    """Shuffle ALL described features into the group structure regardless of influence score.

    Drawing from the entire feature set (grouped + ungrouped, all influence levels)
    gives a true random baseline — the positive is a genuinely random feature,
    not just pre-selected high-impact ones.
    """
    pool = [f for f in all_features if f.get("generated_description")]
    total_slots = sum(len(feats) for feats in group_index.values())
    if len(pool) < total_slots:
        log.warning(
            "[Random] Pool has %d features but %d slots needed — "
            "some groups will have fewer members.",
            len(pool), total_slots,
        )
    rng.shuffle(pool)
    random_index: dict[str, list[dict]] = {}
    idx = 0
    for group_name, feats in group_index.items():
        size = len(feats)
        random_index[group_name] = pool[idx: idx + size]
        idx += size
    return random_index


def load_condition_groups(
    condition: str,
    features: list[dict],
) -> tuple[dict[str, str], dict[str, list[dict]]] | None:
    if condition == "human":
        if not MANUAL_GROUPS_FILE.exists():
            log.info("[human] %s missing — skipping condition.", MANUAL_GROUPS_FILE)
            return None
        with open(MANUAL_GROUPS_FILE, encoding="utf-8") as f:
            groups: dict[str, str] = json.load(f)
        index = build_group_index(features, groups)
        if not index:
            log.warning("[human] No usable groups in %s.", MANUAL_GROUPS_FILE)
            return None
        return groups, index

    if condition == "ours-full":
        if not FEATURE_GROUPS_FILE.exists():
            log.error("[ours-full] %s missing — run generate_supernodes.py first.", FEATURE_GROUPS_FILE)
            return None
        with open(FEATURE_GROUPS_FILE, encoding="utf-8") as f:
            groups = json.load(f)
        index = build_group_index(features, groups)
        return (groups, index) if index else None

    if condition == "ours-no-reconciliation":
        if not FEATURE_GROUPS_PRE3_FILE.exists():
            log.warning("[ours-no-reconciliation] %s missing.", FEATURE_GROUPS_PRE3_FILE)
            return None
        with open(FEATURE_GROUPS_PRE3_FILE, encoding="utf-8") as f:
            groups = json.load(f)
        index = build_group_index(features, groups)
        return (groups, index) if index else None

    cap_n = cap_n_from_condition(condition)
    if cap_n is not None:
        cap_file = ARTIFACTS_DIR / (
            f"feature_groups_{DESCRIPTION_VARIANT}_{GROUPING_VARIANT}_cap{cap_n}.json"
        )
        if not cap_file.exists():
            log.info("[%s] %s missing — skipping condition.", condition, cap_file)
            return None
        with open(cap_file, encoding="utf-8") as f:
            groups = json.load(f)
        index = build_group_index(features, groups)
        return (groups, index) if index else None

    log.error("Unknown condition '%s'.", condition)
    return None


# ---------------------------------------------------------------------------
# Negative pool builders
# ---------------------------------------------------------------------------

def build_medium_neg_pool(features: list[dict], groups: dict[str, str]) -> list[dict]:
    pool: list[dict] = []
    for f in features:
        fid = f.get("id")
        if not fid:
            continue
        gname = groups.get(fid, "Ungrouped")
        if gname.startswith(('Emb: "', 'Output: "')):
            continue
        if gname == "Ungrouped" and f.get("generated_description"):
            pool.append(f)
    return pool


def build_hard_neg_pool(features: list[dict]) -> list[dict]:
    sorted_feats = sorted(
        [f for f in features if "influence_score" in f],
        key=lambda f: float(f.get("influence_score", 0.0)),
        reverse=True,
    )
    return [
        f for f in sorted_feats[GROUPING_TOP_K_SEED:]
        if f.get("generated_description")
    ]


# ---------------------------------------------------------------------------
# Snippet formatting
# ---------------------------------------------------------------------------

def _format_snippet(act: dict) -> str:
    context = act.get("context", "").strip()
    trigger = act.get("trigger", "").strip()
    if trigger and trigger in context:
        return context.replace(trigger, f"<<<{trigger}>>>", 1)
    if trigger:
        return f"{context} [Activates on: <<<{trigger}>>>]"
    return context


def _get_formatted_snippets(feat: dict, max_n: int = 5) -> list[str]:
    return [
        _format_snippet(act)
        for act in feat.get("top_activations", [])[:max_n]
        if act.get("context", "").strip()
    ]


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------

def build_m1_prompt(group_name: str, items: list[tuple[str, bool]]) -> str:
    n = len(items)
    lines = [
        f'Group: "{group_name}"\n',
        f"Below are {n} feature descriptions from neurons inside a language model. "
        "Exactly 1 of these belongs to the group above.\n",
        "Pick the single feature description that best matches the group.\n",
    ]
    for i, (desc, _) in enumerate(items, 1):
        lines.append(f"{i}. {desc}")
    lines.append("\nRespond with the 1-based index of the best match.")
    return "\n".join(lines)


def build_m2_prompt(group_name: str, items: list[tuple[str, bool]], n_pos: int) -> str:
    n = len(items)
    lines = [
        f'Group: "{group_name}"\n',
        f"Below are {n} text excerpts that strongly activated neurons inside a "
        "language model. The key activating tokens are highlighted with <<<>>>. "
        f"Exactly {n_pos} of these come from neurons in this group.\n",
        f"Identify which {n_pos} text excerpts belong to this group.\n",
    ]
    for i, (snippet, _) in enumerate(items, 1):
        lines.append(f"{i}. {snippet}")
    lines.append(
        f"\nRespond with the 1-based indices of the {n_pos} excerpts from this group."
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Individual task runners
# ---------------------------------------------------------------------------

async def run_m1_trial(
    group_name: str,
    prompt: str,
    correct_idx: int,
    n_items: int,
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
) -> float:
    async with sem:
        try:
            resp = await client.beta.chat.completions.parse(
                model=VALIDATION_MODEL,
                messages=[{"role": "user", "content": prompt}],
                response_format=SingleSelection
            )
            parsed = resp.choices[0].message.parsed
            picked = parsed.selected_index if parsed else -1
        except Exception as exc:
            log.warning("[M1] %s: API error — %s", group_name, exc)
            picked = -1

    if picked < 1 or picked > n_items:
        return 0.0
    return 1.0 if picked == correct_idx else 0.0


async def run_m2_task(
    group_name: str,
    prompt: str,
    actual_positive_indices: set[int],
    n_items: int,
    n_expected: int,
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
) -> float:
    async with sem:
        try:
            resp = await client.beta.chat.completions.parse(
                model=VALIDATION_MODEL,
                messages=[{"role": "user", "content": prompt}],
                response_format=FiveSelection
            )
            parsed = resp.choices[0].message.parsed
            if parsed is None:
                return 0.0
            raw_indices = parsed.selected_indices
        except Exception as exc:
            log.warning("[M2] %s: API error — %s", group_name, exc)
            return 0.0

    valid_indices = [i for i in raw_indices if 1 <= i <= n_items]
    unique_valid = list(dict.fromkeys(valid_indices))

    if len(unique_valid) != n_expected:
        return 0.0

    predicted = set(unique_valid)
    return len(predicted & actual_positive_indices) / len(actual_positive_indices)


# ---------------------------------------------------------------------------
# Task generation — M1
# ---------------------------------------------------------------------------

def generate_m1_tasks(
    group_index: dict[str, list[dict]],
    seed: int,
    external_neg_pool: list[dict] | None = None,
) -> list[dict]:
    rng = random.Random(seed)
    tasks: list[dict] = []

    for group_name, pos_features in group_index.items():
        if len(pos_features) < MIN_GROUP_SIZE:
            continue

        neg_pool = external_neg_pool if external_neg_pool is not None else [
            f for gname, feats in group_index.items()
            if gname != group_name
            for f in feats
        ]
        if not neg_pool:
            continue

        test_features = (
            list(pos_features) if len(pos_features) <= MAX_FEATURES_M1
            else rng.sample(pos_features, MAX_FEATURES_M1)
        )

        for pos_feat in test_features:
            n_neg = min(len(neg_pool), N_NEG_FEATURES_M1)
            neg_feats = rng.sample(neg_pool, n_neg)

            items: list[tuple[str, bool]] = [
                (pos_feat.get("generated_description", "No description"), True)
            ] + [
                (f.get("generated_description", "No description"), False)
                for f in neg_feats
            ]
            rng.shuffle(items)

            correct_idx = next(i + 1 for i, (_, is_pos) in enumerate(items) if is_pos)

            tasks.append({
                "group_name": group_name,
                "prompt": build_m1_prompt(group_name, items),
                "correct_idx": correct_idx,
                "n_items": len(items),
            })

    return tasks


# ---------------------------------------------------------------------------
# Task generation — M2
# ---------------------------------------------------------------------------

def generate_m2_tasks(
    group_index: dict[str, list[dict]],
    seed: int,
    external_neg_pool: list[dict] | None = None,
) -> list[dict]:
    rng = random.Random(seed)
    tasks: list[dict] = []

    for group_name, pos_features in group_index.items():
        if len(pos_features) < MIN_GROUP_SIZE:
            continue

        all_pos_snippets = [
            s for f in pos_features for s in _get_formatted_snippets(f)
        ]
        if len(all_pos_snippets) < N_POS_SNIPPETS_M2:
            log.warning("[M2] %s: only %d snippets (need %d), skipping.",
                        group_name, len(all_pos_snippets), N_POS_SNIPPETS_M2)
            continue

        pos_snippets = rng.sample(all_pos_snippets, N_POS_SNIPPETS_M2)

        neg_snippet_pool = (
            [s for f in external_neg_pool for s in _get_formatted_snippets(f)]
            if external_neg_pool is not None
            else [
                s
                for gname, feats in group_index.items()
                if gname != group_name
                for f in feats
                for s in _get_formatted_snippets(f)
            ]
        )
        n_neg = min(len(neg_snippet_pool), N_NEG_SNIPPETS_M2)
        if n_neg == 0:
            log.warning("[M2] %s: no negative snippets available, skipping.", group_name)
            continue
        neg_snippets = rng.sample(neg_snippet_pool, n_neg)

        items: list[tuple[str, bool]] = (
            [(s, True) for s in pos_snippets] +
            [(s, False) for s in neg_snippets]
        )
        rng.shuffle(items)

        actual_positive_indices = {
            i + 1 for i, (_, is_pos) in enumerate(items) if is_pos
        }
        n_pos = len(pos_snippets)

        tasks.append({
            "group_name": group_name,
            "prompt": build_m2_prompt(group_name, items, n_pos),
            "actual_positive_indices": actual_positive_indices,
            "n_items": len(items),
            "n_expected": n_pos,
        })

    return tasks


# ---------------------------------------------------------------------------
# Run-level aggregation
# ---------------------------------------------------------------------------

def _stderr(values: list[float]) -> float:
    n = len(values)
    if n < 2:
        return 0.0
    mean = sum(values) / n
    variance = sum((v - mean) ** 2 for v in values) / (n - 1)
    return math.sqrt(variance / n)


def aggregate_by_run(
    tagged_results: list[tuple[int, str, float]],
) -> tuple[list[dict], dict[str, float]]:
    nested: dict[str, dict[int, list[float]]] = defaultdict(lambda: defaultdict(list))
    for run_idx, group_name, score in tagged_results:
        nested[group_name][run_idx].append(score)

    per_group_stats: list[dict] = []
    for group_name in sorted(nested.keys()):
        run_means: list[float] = []
        total_trials = 0
        for run_idx in sorted(nested[group_name].keys()):
            trials = nested[group_name][run_idx]
            total_trials += len(trials)
            run_means.append(sum(trials) / len(trials))

        mean_acc = sum(run_means) / len(run_means)
        stderr_acc = _stderr(run_means)
        per_group_stats.append({
            "group": group_name,
            "mean_accuracy": round(mean_acc, 4),
            "stderr_accuracy": round(stderr_acc, 4),
            "n_runs": len(run_means),
            "total_trials": total_trials,
        })

    if per_group_stats:
        group_means = [s["mean_accuracy"] for s in per_group_stats]
        macro = {
            "mean_accuracy": round(sum(group_means) / len(group_means), 4),
            "stderr_accuracy": round(_stderr(group_means), 4),
        }
    else:
        macro = {"mean_accuracy": 0.0, "stderr_accuracy": 0.0}

    return per_group_stats, macro


# ---------------------------------------------------------------------------
# Attribution coverage
# ---------------------------------------------------------------------------

def compute_attribution_coverage(
    features: list[dict], groups: dict[str, str]
) -> float:
    id_to_score = {
        f["id"]: float(f.get("influence_score", 0.0))
        for f in features if "id" in f
    }
    total = sum(id_to_score.values())
    if total == 0.0:
        return 0.0
    annotated = sum(
        id_to_score.get(fid, 0.0)
        for fid, gname in groups.items()
        if gname not in ("Ungrouped",)
        and not gname.startswith(('Emb: "', 'Output: "'))
        and fid in id_to_score
    )
    return round(annotated / total, 4)


# ---------------------------------------------------------------------------
# Run all validation for one condition
# ---------------------------------------------------------------------------

async def run_condition(
    label: str,
    group_index: dict[str, list[dict]],
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
    medium_neg_pool: list[dict] | None = None,
) -> dict[str, Any]:
    valid_groups = {k: v for k, v in group_index.items() if len(v) >= MIN_GROUP_SIZE}
    empty_method: dict[str, Any] = {"groups": [], "macro_avg": {"mean_accuracy": 0.0, "stderr_accuracy": 0.0}}
    expected_sources = ("easy", "medium") if DIFFICULTY == "both" else ("medium",)
    if not valid_groups:
        log.warning("[%s] No valid groups for validation.", label)
        return {src: {"method1": empty_method, "method2": empty_method} for src in expected_sources}

    neg_sources: list[tuple[str, list[dict] | None]] = []
    if DIFFICULTY == "both":
        neg_sources.append(("easy", None))
    neg_sources.append(("medium", medium_neg_pool))

    all_m1_specs: list[tuple[str, int, dict]] = []
    all_m2_specs: list[tuple[str, int, dict]] = []

    for neg_source, ext_pool in neg_sources:
        if ext_pool is not None and len(ext_pool) < N_NEG_FEATURES_M1:
            log.warning("[%s/%s] Negative pool too small (%d), skipping.",
                        label, neg_source, len(ext_pool))
            continue
        for run_idx in range(N_RUNS):
            seed = RANDOM_SEED + run_idx
            for spec in generate_m1_tasks(valid_groups, seed, ext_pool):
                all_m1_specs.append((neg_source, run_idx, spec))
            for spec in generate_m2_tasks(valid_groups, seed, ext_pool):
                all_m2_specs.append((neg_source, run_idx, spec))

    log.info("[%s] Launching %d M1 + %d M2 tasks (easy/medium × %d runs)…",
             label, len(all_m1_specs), len(all_m2_specs), N_RUNS)

    m1_coros = [
        run_m1_trial(s["group_name"], s["prompt"], s["correct_idx"], s["n_items"], client, sem)
        for _, _, s in all_m1_specs
    ]
    m2_coros = [
        run_m2_task(s["group_name"], s["prompt"], s["actual_positive_indices"], s["n_items"], s["n_expected"], client, sem)
        for _, _, s in all_m2_specs
    ]

    all_raw = await asyncio.gather(*m1_coros, *m2_coros)
    m1_scores = all_raw[:len(m1_coros)]
    m2_scores = all_raw[len(m1_coros):]

    m1_by_source: dict[str, list[tuple[int, str, float]]] = defaultdict(list)
    m2_by_source: dict[str, list[tuple[int, str, float]]] = defaultdict(list)
    for (src, run_idx, spec), score in zip(all_m1_specs, m1_scores):
        m1_by_source[src].append((run_idx, spec["group_name"], score))
    for (src, run_idx, spec), score in zip(all_m2_specs, m2_scores):
        m2_by_source[src].append((run_idx, spec["group_name"], score))

    results: dict[str, Any] = {}
    for neg_source in expected_sources:
        if neg_source not in m1_by_source and neg_source not in m2_by_source:
            results[neg_source] = {"method1": empty_method, "method2": empty_method}
            continue
        m1_groups, m1_macro = aggregate_by_run(m1_by_source.get(neg_source, []))
        m2_groups, m2_macro = aggregate_by_run(m2_by_source.get(neg_source, []))
        log.info("[%s/%s] M1: %.1f%% ± %.1f%%  M2: %.1f%% ± %.1f%%",
                 label, neg_source,
                 m1_macro["mean_accuracy"] * 100, m1_macro["stderr_accuracy"] * 100,
                 m2_macro["mean_accuracy"] * 100, m2_macro["stderr_accuracy"] * 100)
        results[neg_source] = {
            "method1": {"groups": m1_groups, "macro_avg": m1_macro, "total_trials": len(m1_by_source.get(neg_source, []))},
            "method2": {"groups": m2_groups, "macro_avg": m2_macro, "total_tasks": len(m2_by_source.get(neg_source, []))},
        }

    return results


async def run_random_condition(
    features: list[dict],
    group_index: dict[str, list[dict]],
    client: AsyncOpenAI,
    sem: asyncio.Semaphore,
    medium_neg_pool: list[dict] | None = None,
) -> dict[str, Any]:
    valid_groups = {k: v for k, v in group_index.items() if len(v) >= MIN_GROUP_SIZE}
    use_medium = (DIFFICULTY == "medium")
    neg_pool_arg = medium_neg_pool if use_medium else None
    neg_source_label = "medium" if use_medium else "easy"

    m1_specs: list[tuple[int, dict]] = []
    m2_specs: list[tuple[int, dict]] = []

    for run_idx in range(N_RUNS):
        seed = RANDOM_SEED + run_idx
        rng = random.Random(seed)
        shuffled = create_random_group_index(features, valid_groups, rng)

        for spec in generate_m1_tasks(shuffled, seed, neg_pool_arg):
            m1_specs.append((run_idx, spec))
        for spec in generate_m2_tasks(shuffled, seed, neg_pool_arg):
            m2_specs.append((run_idx, spec))

    log.info("[Random] Launching %d M1 + %d M2 tasks…", len(m1_specs), len(m2_specs))

    m1_coros = [
        run_m1_trial(s["group_name"], s["prompt"], s["correct_idx"], s["n_items"], client, sem)
        for _, s in m1_specs
    ]
    m2_coros = [
        run_m2_task(s["group_name"], s["prompt"], s["actual_positive_indices"], s["n_items"], s["n_expected"], client, sem)
        for _, s in m2_specs
    ]

    all_results = await asyncio.gather(*m1_coros, *m2_coros)
    m1_scores = all_results[:len(m1_coros)]
    m2_scores = all_results[len(m1_coros):]

    m1_tagged = [(ri, s["group_name"], sc) for (ri, s), sc in zip(m1_specs, m1_scores)]
    m2_tagged = [(ri, s["group_name"], sc) for (ri, s), sc in zip(m2_specs, m2_scores)]

    m1_groups, m1_macro = aggregate_by_run(m1_tagged)
    m2_groups, m2_macro = aggregate_by_run(m2_tagged)

    log.info("[Random/%s] M1: %.1f%% ± %.1f%%  M2: %.1f%% ± %.1f%%",
             neg_source_label,
             m1_macro["mean_accuracy"] * 100, m1_macro["stderr_accuracy"] * 100,
             m2_macro["mean_accuracy"] * 100, m2_macro["stderr_accuracy"] * 100)

    return {
        neg_source_label: {
            "method1": {"groups": m1_groups, "macro_avg": m1_macro, "total_trials": len(m1_tagged)},
            "method2": {"groups": m2_groups, "macro_avg": m2_macro, "total_tasks": len(m2_tagged)},
        }
    }


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

def _fmt_macro(d: dict) -> str:
    return f"{d.get('mean_accuracy', 0.0):.1%} ± {d.get('stderr_accuracy', 0.0):.1%}"


def _macro_for(report: dict, condition: str, neg_source: str, method: str) -> dict:
    return (
        report.get("conditions", {})
        .get(condition, {})
        .get(neg_source, {})
        .get(method, {})
        .get("macro_avg", {"mean_accuracy": 0.0, "stderr_accuracy": 0.0})
    )


def write_markdown_report(report: dict, path: Path) -> None:
    n_runs = report.get("n_runs", N_RUNS)
    chance_m1 = 1 / (1 + N_NEG_FEATURES_M1)
    chance_m2 = N_POS_SNIPPETS_M2 / (N_POS_SNIPPETS_M2 + N_NEG_SNIPPETS_M2)

    difficulty = report.get("difficulty", DIFFICULTY)
    sources = ("easy", "medium") if difficulty == "both" else ("medium",)
    conditions = report.get("conditions", {})

    L: list[str] = [
        "# Validation Report",
        "",
        f"**Prompt:** {report.get('prompt', 'Unknown')}",
        f"**Description variant:** `{DESCRIPTION_VARIANT}`  |  **Grouping variant:** `{GROUPING_VARIANT}`",
        f"**Min group size:** {report.get('min_group_size', MIN_GROUP_SIZE)}  |  "
        f"**Difficulty:** {difficulty}",
        f"**Date:** {report.get('timestamp', '')}  |  **Runs:** {n_runs}",
        "",
        "---",
        "",
        "## Method Scores by Condition",
        "",
        f"M1 = 1-in-{1+N_NEG_FEATURES_M1} feature ID (chance {chance_m1:.0%}). "
        f"M2 = {N_POS_SNIPPETS_M2}-in-{N_POS_SNIPPETS_M2+N_NEG_SNIPPETS_M2} text match (chance {chance_m2:.0%}). "
        "Scores are mean ± stderr across runs.",
        "",
    ]

    header_cells = ["Condition"] + [f"M1 ({s})" for s in sources] + [f"M2 ({s})" for s in sources] + ["Coverage", "Groups"]
    L.append("| " + " | ".join(header_cells) + " |")
    L.append("|" + "|".join([":--"] + ["---:"] * (len(header_cells) - 1)) + "|")

    for cond in sorted(conditions.keys(), key=condition_sort_key):
        c = conditions[cond]
        if c.get("skipped"):
            L.append(f"| **{cond}** | _skipped: {c.get('reason','')}_ |")
            continue
        cov = c.get("attribution_coverage")
        cov_str = f"{cov:.1%}" if cov is not None else "—"
        n_valid = c.get("n_groups_valid")
        groups_str = f"{n_valid}/{c.get('n_groups_total', '?')}" if n_valid is not None else "—"
        cells = [f"**{cond}**"]
        for s in sources:
            cells.append(_fmt_macro(_macro_for(report, cond, s, "method1")))
        for s in sources:
            cells.append(_fmt_macro(_macro_for(report, cond, s, "method2")))
        cells += [cov_str, groups_str]
        L.append("| " + " | ".join(cells) + " |")
    L += ["", "---", ""]

    detail_cond = "ours-full" if "ours-full" in conditions else next(iter(conditions), None)
    if detail_cond:
        for s in sources:
            m1_groups = conditions.get(detail_cond, {}).get(s, {}).get("method1", {}).get("groups", [])
            if not m1_groups:
                continue
            L += [
                f"## Per-Group Detail — {detail_cond} / {s}",
                "",
                "| Group | M1 Accuracy | ±Stderr | Trials |",
                "|:--|---:|---:|---:|",
            ]
            for sg in sorted(m1_groups, key=lambda x: x["mean_accuracy"], reverse=True):
                L.append(
                    f"| {sg['group'][:55]} "
                    f"| {sg['mean_accuracy']:.1%} "
                    f"| {sg['stderr_accuracy']:.1%} "
                    f"| {sg['total_trials']} |"
                )
            L += [""]
            break

    L += [
        "---",
        "",
        f"*Generated {report.get('timestamp', '')} · "
        f"desc=`{DESCRIPTION_VARIANT}` · group=`{GROUPING_VARIANT}` · "
        f"min_group_size={report.get('min_group_size', MIN_GROUP_SIZE)}*",
    ]

    path.write_text("\n".join(L) + "\n", encoding="utf-8")
    log.info("Markdown report saved → %s", path)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _read_prompt_from_graph() -> str:
    try:
        with open(GRAPH_FILE, encoding="utf-8") as f:
            data = json.load(f)
        meta = data.get("metadata", {})
        prompt = meta.get("prompt", "")
        if not prompt:
            tokens = meta.get("prompt_tokens", [])
            prompt = "".join(str(t) for t in tokens)
        return prompt or GRAPH_FILE.stem
    except Exception:
        return GRAPH_FILE.stem


def _count_named_groups(groups_raw: dict[str, str]) -> int:
    return len({
        g for g in groups_raw.values()
        if g != "Ungrouped" and not g.startswith(('Emb: "', 'Output: "'))
    })


def _resolve_requested_conditions() -> list[str]:
    available = all_available_conditions()
    raw = VALIDATION_CONDITIONS.strip()
    if not raw:
        return list(available)
    requested = [c.strip() for c in raw.split(",") if c.strip()]
    invalid = [
        c for c in requested
        if c not in available and not _OURS_CAP_RE.match(c)
    ]
    if invalid:
        log.error("Unknown VALIDATION_CONDITIONS values: %s. Available: %s", invalid, available)
        sys.exit(1)
    return requested


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def main_async() -> None:
    if not FEATURE_DESCRIPTIONS_FILE.exists():
        log.error("Missing %s — run generate_description.py first.", FEATURE_DESCRIPTIONS_FILE)
        sys.exit(1)
    with open(FEATURE_DESCRIPTIONS_FILE, encoding="utf-8") as f:
        features: list[dict] = json.load(f)

    requested = _resolve_requested_conditions()
    log.info("Conditions: %s", requested)
    log.info("Min group size: %d  |  Difficulty: %s", MIN_GROUP_SIZE, DIFFICULTY)

    client = AsyncOpenAI()
    sem = asyncio.Semaphore(CONCURRENCY_LIMIT)

    loaded: dict[str, tuple[dict[str, str], dict[str, list[dict]]]] = {}
    skipped: dict[str, str] = {}
    for cond in requested:
        if cond == "random":
            base = load_condition_groups("ours-full", features)
            if base is None:
                skipped[cond] = "ours-full base groups unavailable"
                continue
            loaded[cond] = base
        else:
            res = load_condition_groups(cond, features)
            if res is None:
                skipped[cond] = "data file missing"
                continue
            loaded[cond] = res

    coros: list[Any] = []
    cond_order: list[str] = []
    for cond in requested:
        if cond not in loaded:
            continue
        groups_raw, group_index = loaded[cond]
        medium_neg_pool = build_medium_neg_pool(features, groups_raw)
        log.info("[%s] Negative pool (medium): %d features", cond, len(medium_neg_pool))
        if cond == "random":
            coros.append(run_random_condition(features, group_index, client, sem, medium_neg_pool))
        else:
            coros.append(run_condition(cond, group_index, client, sem, medium_neg_pool))
        cond_order.append(cond)

    gathered = await asyncio.gather(*coros) if coros else []
    n_cond = len(cond_order)
    cond_results_raw = gathered[:n_cond]

    condition_results: dict[str, Any] = {}
    for cond, out in zip(cond_order, cond_results_raw):
        groups_raw, group_index = loaded[cond]
        condition_results[cond] = {
            **out,
            "attribution_coverage": compute_attribution_coverage(features, groups_raw),
            "n_groups_total": _count_named_groups(groups_raw),
            "n_groups_valid": sum(1 for v in group_index.values() if len(v) >= MIN_GROUP_SIZE),
        }
    for cond, reason in skipped.items():
        condition_results[cond] = {"skipped": True, "reason": reason}

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    prompt_text = _read_prompt_from_graph()
    report: dict[str, Any] = {
        "prompt": prompt_text,
        "timestamp": timestamp,
        "n_runs": N_RUNS,
        "min_group_size": MIN_GROUP_SIZE,
        "difficulty": DIFFICULTY,
        "design": {
            "method1": f"1-in-{1+N_NEG_FEATURES_M1} feature identification (chance={1/(1+N_NEG_FEATURES_M1):.0%})",
            "method2": f"{N_POS_SNIPPETS_M2}-in-{N_POS_SNIPPETS_M2+N_NEG_SNIPPETS_M2} text snippet matching (chance={N_POS_SNIPPETS_M2/(N_POS_SNIPPETS_M2+N_NEG_SNIPPETS_M2):.0%})",
            "aggregation": "per-group run-level means, then mean ± stderr across runs",
            "neg_sources": "medium=Ungrouped/unassigned features (excluding Emb/Output)",
            "conditions": {
                "random": "ours-full groups, features shuffled across them",
                "human": "manual_groups.json — human labels from Neuronpedia share URL supernodes",
                "ours-full": "auto pipeline output after phase-3 reconciliation (no feature cap)",
                "ours-no-reconciliation": "auto pipeline output before phase-3 (snapshot)",
                "ours-cap<N>": "phase-2 cap sweep variant — only the top N most influential "
                               "features were fed to grouping (50 = phase 1 only). Phase 3 "
                               "still runs on top.",
            },
        },
        "conditions": condition_results,
    }

    with open(VALIDATION_REPORT_FILE, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2, ensure_ascii=False)
    log.info("Validation report saved → %s", VALIDATION_REPORT_FILE)

    write_markdown_report(report, VALIDATION_MARKDOWN_FILE)

    history: list[dict] = []
    if VALIDATION_HISTORY_FILE.exists():
        try:
            with open(VALIDATION_HISTORY_FILE, encoding="utf-8") as f:
                history = json.load(f)
        except json.JSONDecodeError:
            history = []
    history.append(report)
    with open(VALIDATION_HISTORY_FILE, "w", encoding="utf-8") as f:
        json.dump(history, f, indent=2, ensure_ascii=False)
    log.info("Appended to history (%d total) → %s", len(history), VALIDATION_HISTORY_FILE)

    # Console summary
    chance_m1 = 1 / (1 + N_NEG_FEATURES_M1)
    chance_m2 = N_POS_SNIPPETS_M2 / (N_POS_SNIPPETS_M2 + N_NEG_SNIPPETS_M2)

    print(f"\n{'='*84}")
    print(f"  VALIDATION SUMMARY  ({N_RUNS} runs · min_group_size={MIN_GROUP_SIZE} · difficulty={DIFFICULTY})")
    print(f"  M1 chance={chance_m1:.0%}  M2 chance={chance_m2:.0%}")
    print(f"{'='*84}")

    sources = ("easy", "medium") if DIFFICULTY == "both" else ("medium",)
    header = (
        f"  {'Condition':<26}"
        + "".join(f"{'M1 ' + s:>16}" for s in sources)
        + "".join(f"{'M2 ' + s:>16}" for s in sources)
        + f"{'Coverage':>10}{'Groups':>10}"
    )
    print(header)
    print("  " + "-" * (len(header) - 2))
    for cond in sorted(condition_results.keys(), key=condition_sort_key):
        c = condition_results[cond]
        if c.get("skipped"):
            print(f"  {cond:<26}  skipped: {c.get('reason','')}")
            continue
        row = f"  {cond:<26}"
        for s in sources:
            m = _macro_for(report, cond, s, "method1")
            row += f"{m['mean_accuracy']*100:>8.1f}±{m['stderr_accuracy']*100:.1f}%  "
        for s in sources:
            m = _macro_for(report, cond, s, "method2")
            row += f"{m['mean_accuracy']*100:>8.1f}±{m['stderr_accuracy']*100:.1f}%  "
        cov = c.get("attribution_coverage")
        cov_str = f"{cov*100:.1f}%" if cov is not None else "  —  "
        n_valid = c.get("n_groups_valid", 0)
        n_total = c.get("n_groups_total", 0)
        row += f"{cov_str:>10}{f'{n_valid}/{n_total}':>10}"
        print(row)

    print(f"{'='*84}\n")


def main() -> None:
    asyncio.run(main_async())


if __name__ == "__main__":
    main()